import Image from "next/image";
import Link from "next/link";

import {ProductCard} from "@/components/product-card";
import {getCategories,getHomepage,getProducts} from "@/lib/api";

type Content={eyebrow?:string;title?:string;subtitle?:string;cta_label?:string;cta_href?:string;media_url?:string;mobile_media_url?:string;media_type?:string;poster_url?:string;alignment?:"left"|"center"|"right"};
const data=(sections:Awaited<ReturnType<typeof getHomepage>>,key:string)=>sections.find(section=>section.key===key)?.content as Content|undefined;
function Media({content,priority=false}:{content?:Content;priority?:boolean}){if(!content?.media_url)return <div className="media-placeholder" aria-label="Место для медиа"/>;if(content.mobile_media_url&&content.media_type!=="video")return <picture className="cover-picture"><source media="(max-width: 700px)" srcSet={content.mobile_media_url}/><img className="cover-media" src={content.media_url} alt=""/></picture>;return content.media_type==="video"?<video className="cover-media" src={content.media_url} poster={content.poster_url} autoPlay muted loop playsInline preload={priority?"auto":"metadata"}/>:<Image className="cover-media" src={content.media_url} alt="" fill priority={priority} sizes="100vw"/>}
function Action({content}:{content?:Content}){return content?.cta_label&&content.cta_href?<Link className="btn light" href={content.cta_href}>{content.cta_label}</Link>:null}
export default async function HomePage(){const [sections,categories,newProducts,featuredProducts]=await Promise.all([getHomepage(),getCategories(),getProducts({is_new:true,sort:"newest",limit:6}),getProducts({featured:true,limit:4})]);const hero=data(sections,"hero"),cinematic=data(sections,"cinematic"),promo=data(sections,"promo"),newBlock=data(sections,"new"),featuredBlock=data(sections,"featured"),categoryBlock=data(sections,"categories");const ordered=sections.length?sections.filter(section=>section.enabled&&section.status==="published").sort((a,b)=>a.sort_order-b.sort_order).map(section=>section.key):["hero","categories","new","cinematic","featured","promo","benefits"];
 const blocks:{[key:string]:React.ReactNode}={
 hero:<section className="v2-hero" key="hero"><Media content={hero} priority/><div className={`hero-panel hero-align-${hero?.alignment||"left"}`}><span className="eyebrow">{hero?.eyebrow||"Новая глава"}</span><h1>{hero?.title||"Коллекция ждёт своего образа"}</h1><p>{hero?.subtitle||"Выберите силуэт, который говорит за вас."}</p>{hero?.cta_label&&hero?.cta_href?<Action content={hero}/>:<Link className="btn light" href="/catalog">Смотреть коллекцию</Link>}</div></section>,
 categories:<section className="section v2-section" key="categories"><div className="wrap"><div className="section-heading"><span className="eyebrow">{categoryBlock?.eyebrow||"Выбор"}</span><h2>{categoryBlock?.title||"Категории"}</h2></div><div className="editorial-strip">{categories.data.map((category,index)=><Link className={`editorial-category cat-${index%3}`} href={`/catalog?category=${category.slug}`} key={category.slug}>{category.media_url?<Image src={category.media_url} alt={category.name} fill sizes="(max-width:900px) 76vw, 32vw"/>:<div className="media-placeholder"/>}<span>{category.name}<b>↗</b></span></Link>)}</div>{!categories.data.length&&<p className="empty-copy">Категории появятся здесь после настройки в админ-панели.</p>}</div></section>,
 new:<ProductShelf key="new" eyebrow={newBlock?.eyebrow||"Свежий взгляд"} title={newBlock?.title||"Новинки"} href={newBlock?.cta_href||"/catalog?sort=newest"} label={newBlock?.cta_label||"Все новинки"} products={newProducts}/>,
 cinematic:<section className="cinematic" key="cinematic"><Media content={cinematic}/><div className="cinematic-copy"><span className="eyebrow">{cinematic?.eyebrow||"В фокусе"}</span><h2>{cinematic?.title||"История, рассказанная силуэтом"}</h2>{cinematic?.subtitle&&<p>{cinematic.subtitle}</p>}<Action content={cinematic}/></div></section>,
 featured:<ProductShelf key="featured" eyebrow={featuredBlock?.eyebrow||"Избранное"} title={featuredBlock?.title||"Хиты"} href={featuredBlock?.cta_href||"/catalog"} label={featuredBlock?.cta_label||"Смотреть каталог"} products={featuredProducts}/>,
 promo:<section className="promo-block wrap" key="promo"><div className="promo-media"><Media content={promo}/></div><div><span className="eyebrow">{promo?.eyebrow||"Для вас"}</span><h2>{promo?.title||"Ваш следующий образ начинается здесь"}</h2>{promo?.subtitle&&<p>{promo.subtitle}</p>}<Action content={promo}/></div></section>,
 benefits:<section className="v2-benefits" key="benefits">{["Доставка","Возврат","Оплата","Поддержка"].map((item,index)=><div key={item}><span>0{index+1}</span><strong>{item}</strong></div>)}</section>
 };return <main>{ordered.map(key=>blocks[key]).filter(Boolean)}</main>}
function ProductShelf({eyebrow,title,href,label,products}:{eyebrow:string;title:string;href:string;label:string;products:Awaited<ReturnType<typeof getProducts>>}){return <section className="section v2-section wrap"><div className="section-heading row"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><Link className="text-link" href={href}>{label} ↗</Link></div>{products.length?<div className="product-grid editorial-products">{products.map(product=><ProductCard product={product} key={product.id}/>)}</div>:<p className="empty-copy">Товары появятся здесь после публикации.</p>}</section>}
