"use client";

import {FormEvent, useEffect, useState} from "react";
import Link from "next/link";
import {adminApi} from "@/lib/admin-api";
import {rub} from "@/lib/api";

type Order={id:string;public_number:string;status:string;customer_name:string;phone:string;total:number;currency:string;created_at:string;updated_at:string};
type OrderDetail=Order&{email:string|null;whatsapp:string|null;delivery_method:string;delivery_address:string|null;comment:string|null;internal_note:string|null;items:{id:string;product_name:string;variant_description:string;sku:string;quantity:number;unit_price:number;total_price:number}[];history:{id:string;status:string;note:string|null;actor:string;created_at:string}[]};
const statuses=["NEW","CONFIRMED","PROCESSING","READY","COMPLETED","CANCELLED"];
const date=(value:string)=>new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));

export function AdminOrders(){const [orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState("");const load=async()=>{try{const params=new URLSearchParams();if(q)params.set("q",q);if(status)params.set("status_filter",status);setOrders(await adminApi<Order[]>(`/orders?${params}`))}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить заказы")}};useEffect(()=>{load()},[]);return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">admin</p><h1>Заказы</h1></div></header>{error&&<p className="admin-error">{error}</p>}<section className="admin-panel"><div className="admin-toolbar"><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Номер, имя или телефон"/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">Все статусы</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><button className="btn" onClick={load}>Найти</button></div><div className="admin-product-list">{orders.map(order=><article className="admin-product-row" key={order.id}><div><strong>{order.public_number} · {order.customer_name}</strong><span>{order.status} · {rub(order.total)} · {order.phone} · {date(order.created_at)}</span></div><Link className="btn" href={`/admin/orders/${order.id}`}>Открыть</Link></article>)}{!orders.length&&<p className="muted">Заказы пока не созданы.</p>}</div></section></main>}

export function AdminOrderDetail({orderId}:{orderId:string}){const [order,setOrder]=useState<OrderDetail|null>(null),[status,setStatus]=useState(""),[note,setNote]=useState(""),[internalNote,setInternalNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=async()=>{try{const value=await adminApi<OrderDetail>(`/orders/${orderId}`);setOrder(value);setStatus(value.status);setInternalNote(value.internal_note||"")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить заказ")}};useEffect(()=>{load()},[orderId]);const save=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const value=await adminApi<OrderDetail>(`/orders/${orderId}`,{method:"PUT",body:JSON.stringify({status,internal_note:internalNote,note})});setOrder(value);setNote("")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить заказ")}finally{setBusy(false)}};if(!order)return <main className="admin-shell"><p>{error||"Загружаем заказ…"}</p></main>;return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">Заказ {order.public_number}</p><h1>{order.customer_name}</h1></div><Link className="btn" href="/admin/orders">К заказам</Link></header>{error&&<p className="admin-error">{error}</p>}<section className="admin-panel order-details"><p><strong>{order.status}</strong> · {rub(order.total)} · {date(order.created_at)}</p><p>{order.phone}{order.email?` · ${order.email}`:""}</p>{order.delivery_address&&<p>Адрес: {order.delivery_address}</p>}{order.comment&&<p>Комментарий клиента: {order.comment}</p>}<h2>Состав</h2>{order.items.map(item=><article className="admin-product-row" key={item.id}><div><strong>{item.product_name}</strong><span>{item.variant_description} · SKU {item.sku} · {item.quantity} × {rub(item.unit_price)}</span></div><strong>{rub(item.total_price)}</strong></article>)}</section><form className="admin-panel admin-form" onSubmit={save}><h2>Обработка</h2><label>Статус<select value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><label>Внутренняя заметка<textarea value={internalNote} onChange={event=>setInternalNote(event.target.value)}/></label><label>Комментарий к смене статуса<textarea value={note} onChange={event=>setNote(event.target.value)}/></label><button className="btn dark" disabled={busy}>{busy?"Сохраняем…":"Сохранить"}</button></form><section className="admin-panel"><h2>История</h2>{order.history.map(item=><article className="admin-product-row" key={item.id}><div><strong>{item.status}</strong><span>{item.actor} · {date(item.created_at)}{item.note?` · ${item.note}`:""}</span></div></article>)}</section></main>}
