import { beforeEach, describe, expect, it } from "vitest";
import { ContentService, type MutationActor } from "../src/content-service";
import { AppError } from "../src/errors";
import { assertWritePath, type GitWriterPort } from "../src/github-writer";
import type { AdminStore, AuditInput, IdempotencyState, SessionInput } from "../src/store";
import { createApp } from "../src/index";
import type { AdminSession, AdminUser, ContentKey, Env, GitCommitChange, GitCommitResult, GitHubDocument, GitUploadAsset } from "../src/types";

const actor: MutationActor = { id: "admin-1", role: "ADMIN", requestId: "request-1" };
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const text = new TextDecoder();
const initialDocuments: Record<ContentKey, Record<string, unknown>> = {
  products: { products: [{ id: "product-1", name: "Платье", article: null, slug: "plate", short_description: "Короткое описание", description: "Полное описание товара", category: "Женское", category_slug: "zhenskoe", price: 1000, compare_at_price: 1200, currency: "RUB", status: "published", is_featured: false, is_new: false, collections: ["novinki"], media: [{ id: "11111111-1111-4111-8111-111111111111", type: "image", url: "/uploads/22222222-2222-4222-8222-222222222222.jpg", alt_text: "", sort_order: 0, is_primary: true, is_secondary: false, variant_id: null }], variants: [{ id: "variant-1", sku: "SKU-1", options: { size: "M", color: "black" }, stock_quantity: 4, is_active: true, media: [] }], attributes: [] }] },
  categories: { categories: [{ name: "Женское", slug: "zhenskoe", description: null, media_url: null, sort_order: 0, is_visible: true }, { name: "Свободная", slug: "free", description: null, media_url: null, sort_order: 1, is_visible: true }] },
  collections: { collections: [{ name: "Новинки", slug: "novinki", description: null, media_url: null, sort_order: 0, is_visible: true }, { name: "Свободная", slug: "free", description: null, media_url: null, sort_order: 1, is_visible: true }] },
  homepage: { sections: [{ key: "hero", enabled: true, sort_order: 0, status: "published", content: { title: "До" } }] },
  settings: { settings: { store_name: "Зиярат", whatsapp: "", telegram: "", phone: "", email: "", delivery: "", returns: "", footer: "", seo_title: "", seo_description: "" } }
};

class MemoryStore implements AdminStore {
  readonly auditEvents: AuditInput[] = [];
  users = new Map<string, AdminUser>(); sessions = new Map<string, AdminSession>(); idempotency = new Map<string, { requestHash: string; state: "PENDING" | "COMPLETED" | "FAILED"; response?: unknown; status?: number }>(); jobs: Record<string, unknown>[] = [];
  constructor(role: "ADMIN" | "MODERATOR" = "ADMIN") { const now = Date.now(); this.users.set("admin-1", { id: "admin-1", loginNormalized: "admin", displayLogin: "admin", passwordHash: "password123", passwordAlgorithm: "test", role, isActive: true, sessionVersion: 1, passwordChangedAt: now, lastLoginAt: null, createdAt: now, updatedAt: now }); }
  async findUserByLogin(login: string) { return [...this.users.values()].find((user) => user.loginNormalized === login) ?? null; } async findUserById(id: string) { return this.users.get(id) ?? null; } async markUserLoggedIn() {}
  async createSession(input: SessionInput) { this.sessions.set(input.id, { ...input, lastSeenAt: input.createdAt, revokedAt: null }); } async findSession(id: string) { return this.sessions.get(id) ?? null; } async touchSession() {} async revokeSession(id: string, now: number) { const session = this.sessions.get(id); if (session) session.revokedAt = now; } async revokeUserSessions() {} async changePassword() {}
  async recordAttempt() { return { allowed: true, retryAfterSeconds: 0 }; } async clearAttempts() {} async audit(input: AuditInput) { this.auditEvents.push(input); }
  async beginIdempotency(input: { actorUserId: string; operation: string; keyHash: string; requestHash: string }): Promise<IdempotencyState> { const key = `${input.actorUserId}:${input.operation}:${input.keyHash}`; const old = this.idempotency.get(key); if (!old) { this.idempotency.set(key, { requestHash: input.requestHash, state: "PENDING" }); return { kind: "new" }; } if (old.requestHash !== input.requestHash) return { kind: "conflict" }; if (old.state === "PENDING") return { kind: "pending" }; if (old.state === "FAILED") return { kind: "failed", status: old.status ?? 500, response: old.response ?? {} }; return { kind: "completed", status: old.status ?? 500, response: old.response ?? {} }; }
  async completeIdempotency(input: { actorUserId: string; operation: string; keyHash: string; status: number; response: unknown }) { const value = this.idempotency.get(`${input.actorUserId}:${input.operation}:${input.keyHash}`); if (value) Object.assign(value, { state: "COMPLETED", status: input.status, response: input.response }); }
  async failIdempotency(input: { actorUserId: string; operation: string; keyHash: string; status: number; response: unknown }) { const value = this.idempotency.get(`${input.actorUserId}:${input.operation}:${input.keyHash}`); if (value) Object.assign(value, { state: "FAILED", status: input.status, response: input.response }); }
  async createPublishJob(input: { actorUserId: string; commitSha: string; paths: string[]; now: number }) { this.jobs.push({ github_commit_sha: input.commitSha, status: "awaiting_run", paths_json: JSON.stringify(input.paths), created_at: input.now, updated_at: input.now }); }
  async inventoryHistory(productId: string) { return this.auditEvents.filter((event) => event.action === "inventory.adjusted" && event.metadata?.product_id === productId).map((event) => ({ ...event })); } async publishJob(sha: string) { return this.jobs.find((job) => job.github_commit_sha === sha) ?? null; } async latestPublishJob() { return this.jobs.at(-1) ?? null; } async updatePublishJob(sha: string, status: string, url: string | null) { const job = this.jobs.find((value) => value.github_commit_sha === sha); if (job) Object.assign(job, { status, deployment_url: url }); }
}

class FakeWriter implements GitWriterPort {
  docs = clone(initialDocuments); revisions: Record<ContentKey, string> = { products: "products-1", categories: "categories-1", collections: "collections-1", homepage: "homepage-1", settings: "settings-1" }; branch = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"; commits = 0; uploads: GitUploadAsset[] = [{ id: "22222222-2222-4222-8222-222222222222", path: "apps/web/public/uploads/22222222-2222-4222-8222-222222222222.jpg", url: "/uploads/22222222-2222-4222-8222-222222222222.jpg" }]; snapshots = new Map<string, Record<ContentKey, Record<string, unknown>>>();
  constructor() { this.snapshots.set("aaaaaaa", clone(this.docs)); }
  async readByKey(key: ContentKey): Promise<GitHubDocument> { return { path: `content/${key}.json` as GitHubDocument["path"], sha: this.revisions[key], value: clone(this.docs[key]) }; }
  async readByKeyAt(key: ContentKey, ref: string): Promise<GitHubDocument> { const snapshot = this.snapshots.get(ref); if (!snapshot) throw new AppError(404, "not_found", "commit не найден"); return { path: `content/${key}.json` as GitHubDocument["path"], sha: this.revisions[key], value: clone(snapshot[key]) }; }
  async head() { return this.branch; }
  async commit(changes: GitCommitChange[], input: { message: string; expectedRevisions?: Partial<Record<ContentKey, string>>; expectedHead?: string }): Promise<GitCommitResult> {
    if (input.expectedHead && input.expectedHead !== this.branch) throw new AppError(409, "CONTENT_CONFLICT", "branch changed");
    for (const [key, expected] of Object.entries(input.expectedRevisions ?? {}) as [ContentKey, string][]) if (this.revisions[key] !== expected) throw new AppError(409, "CONTENT_CONFLICT", "stale", { ETag: `"${this.revisions[key]}"` });
    const revisions: Partial<Record<ContentKey, string>> = {}; this.commits += 1;
    for (const change of changes) { assertWritePath(change.path); const key = (Object.keys(this.revisions) as ContentKey[]).find((candidate) => change.path === `content/${candidate}.json`); if (key && change.bytes) { this.docs[key] = JSON.parse(text.decode(change.bytes)); this.revisions[key] = `${key}-${this.commits + 1}`; revisions[key] = this.revisions[key]; } }
    const sha = `abcdef${this.commits.toString(16)}`; this.branch = `${sha}${"0".repeat(40 - sha.length)}`; this.snapshots.set(sha, clone(this.docs)); return { commitSha: sha, revisions };
  }
  async listUploads() { return clone(this.uploads); } async workflowForCommit() { return null; } async history() { return [{ sha: "aaaaaaa", message: "initial", createdAt: "2026-01-01T00:00:00Z" }]; }
}

const product = (overrides: Record<string, unknown> = {}) => ({ name: "Новое платье", slug: "new-dress", short_description: "Короткое описание", description: "Подробное описание нового платья", category_id: "zhenskoe", collection_ids: ["novinki"], price: 2200, compare_at_price: 2500, status: "published", variants: [{ size: "M", color: "black", stock_quantity: 2 }], media: [], attributes: [], ...overrides });

describe("Phase 2 ContentService", () => {
  let store: MemoryStore; let writer: FakeWriter; let service: ContentService;
  beforeEach(() => { store = new MemoryStore(); writer = new FakeWriter(); service = new ContentService(writer, store); });
  it("creates, updates and deletes a product with one commit per successful mutation", async () => { const created = await service.createProduct(product(), "products-1", actor); expect(created.revision).toBe("products-2"); const item = (writer.docs.products.products as { id: string }[]).at(-1); expect(item?.id).toMatch(/^[0-9a-f-]{36}$/u); await service.updateProduct(item?.id ?? "", product({ name: "Новое имя" }), "products-2", actor); await service.deleteProduct(item?.id ?? "", "products-3", actor); expect(writer.commits).toBe(3); expect(store.jobs).toHaveLength(3); });
  it("previews a validated product update without creating a commit or audit event", async () => { const preview = await service.previewProductUpdate("product-1", { description: "Новое безопасное описание" }, "products-1"); expect(preview.before.description).toBe("Полное описание товара"); expect(preview.after.description).toBe("Новое безопасное описание"); expect(preview.revision).toBe("products-1"); expect(writer.commits).toBe(0); expect(store.auditEvents).toHaveLength(0); });
  it("rejects duplicate slugs, invalid references, invalid prices, and stale revisions", async () => { await expect(service.createProduct(product({ slug: "plate" }), "products-1", actor)).rejects.toMatchObject({ code: "duplicate_slug" }); await expect(service.createProduct(product({ category_id: "missing" }), "products-1", actor)).rejects.toMatchObject({ code: "invalid_category" }); await expect(service.createProduct(product({ collection_ids: ["missing"] }), "products-1", actor)).rejects.toMatchObject({ code: "invalid_collection" }); await expect(service.createProduct(product({ compare_at_price: 1000 }), "products-1", actor)).rejects.toMatchObject({ code: "validation_error" }); await expect(service.createProduct(product(), "stale", actor)).rejects.toMatchObject({ status: 409, code: "CONTENT_CONFLICT" }); });
  it("updates inventory atomically and forbids negative stock", async () => { await service.adjustInventory("variant-1", { delta: -2, reason: "sale" }, "products-1", actor); expect((writer.docs.products.products as { variants: { stock_quantity: number }[] }[])[0].variants[0].stock_quantity).toBe(2); await expect(service.adjustInventory("variant-1", { delta: -3, reason: "sale" }, "products-1", actor)).rejects.toMatchObject({ code: "CONTENT_CONFLICT" }); await expect(service.adjustInventory("variant-1", { delta: -3, reason: "sale" }, "products-2", actor)).rejects.toMatchObject({ code: "negative_stock" }); });
  it("deletes only unreferenced taxonomy entries", async () => { await service.deleteTaxonomy("categories", "free", "categories-1", actor); await expect(service.deleteTaxonomy("categories", "zhenskoe", "categories-2", actor)).rejects.toMatchObject({ code: "RESOURCE_IN_USE" }); await service.deleteTaxonomy("collections", "free", "collections-1", actor); await expect(service.deleteTaxonomy("collections", "novinki", "collections-2", actor)).rejects.toMatchObject({ code: "RESOURCE_IN_USE" }); });
  it("creates a compensating homepage rollback commit without moving branch history", async () => { await service.updateHomepage("hero", { enabled: true, sort_order: 0, status: "published", content: { title: "После" } }, "homepage-1", actor); const beforeHead = writer.branch; const restored = await service.rollbackHomepage("hero", "aaaaaaa", "homepage-2", actor); expect(restored.commit_sha).not.toBe("aaaaaaa"); expect(writer.branch).not.toBe(beforeHead); expect((writer.docs.homepage.sections as { content: { title: string } }[])[0].content.title).toBe("До"); });
  it("does not delete a referenced media asset and cannot address arbitrary paths", async () => { await expect(service.deleteMedia("22222222-2222-4222-8222-222222222222", writer.branch, actor)).rejects.toMatchObject({ code: "RESOURCE_IN_USE" }); expect(() => assertWritePath(".github/workflows/pages.yml")).toThrow(/path/i); expect(() => assertWritePath("apps/web/app/page.tsx")).toThrow(/path/i); expect(() => assertWritePath("content/other.json")).toThrow(/path/i); });
});

describe("Phase 2 HTTP safety and idempotency", () => {
  let store: MemoryStore; let writer: FakeWriter;
  const env = { DB: {} as D1Database, ENVIRONMENT: "production", ALLOWED_ORIGINS: "https://shop.example.com", GITHUB_OWNER: "owner", GITHUB_REPO: "repo", GITHUB_REF: "main", WRITES_ENABLED: "true", IP_HASH_PEPPER: "pepper" } satisfies Env;
  const config = { environment: "production" as const, allowedOrigins: new Set(["https://shop.example.com"]), githubOwner: "owner", githubRepo: "repo", githubRef: "main", writesEnabled: true, ipHashPepper: "pepper" };
  const call = (path: string, init: RequestInit = {}) => new Request(`https://worker.example${path}`, { ...init, headers: { Origin: "https://shop.example.com", ...init.headers } });
  const app = () => createApp(env, { store, writer, config, hasher: { algorithm: "test", hash: async (value) => value, verify: async (value, hash) => value === hash } });
  const login = async () => { const response = await app().fetch(call("/api/admin/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ login: "admin", password: "password123" }) })); const body = await response.json() as { csrf_token: string }; const raw = response.headers.get("set-cookie") ?? ""; const session = raw.match(/za_admin_session=([^;]+)/u)?.[1] ?? ""; const csrfCookie = raw.match(/za_admin_csrf=([^;]+)/u)?.[1] ?? ""; return { cookie: `za_admin_session=${session}; za_admin_csrf=${csrfCookie}`, csrf: body.csrf_token }; };
  const upload = async (cookie: string, csrf: string, bytes: number[], type: string, key: string) => { const form = new FormData(); form.append("file", new Blob([new Uint8Array(bytes)], { type }), "unsafe-name.bin"); return app().fetch(call("/api/admin/media", { method: "POST", headers: { Cookie: cookie, "X-CSRF-Token": csrf, "If-Match": writer.branch, "Idempotency-Key": key }, body: form })); };
  beforeEach(() => { store = new MemoryStore(); writer = new FakeWriter(); });
  it("allows a MODERATOR product write but rejects settings and rollback", async () => { store = new MemoryStore("MODERATOR"); const { cookie, csrf } = await login(); const headers = { Cookie: cookie, "X-CSRF-Token": csrf, "Content-Type": "application/json", "If-Match": "products-1", "Idempotency-Key": "product-create-key-0001" }; expect((await app().fetch(call("/api/admin/products", { method: "POST", headers, body: JSON.stringify(product()) }))).status).toBe(201); expect((await app().fetch(call("/api/admin/settings", { method: "PUT", headers: { ...headers, "If-Match": "settings-1", "Idempotency-Key": "settings-key-0000001" }, body: JSON.stringify({ store_name: "x" }) }))).status).toBe(403); expect((await app().fetch(call("/api/admin/homepage/hero/rollback/aaaaaaa", { method: "POST", headers: { ...headers, "If-Match": "homepage-1", "Idempotency-Key": "rollback-key-0000001" } }))).status).toBe(403); });
  it("returns the original response for duplicate delivery and rejects a reused key with a different payload", async () => { const { cookie, csrf } = await login(); const headers = { Cookie: cookie, "X-CSRF-Token": csrf, "Content-Type": "application/json", "If-Match": "products-1", "Idempotency-Key": "idempotency-key-00001" }; const first = await app().fetch(call("/api/admin/products", { method: "POST", headers, body: JSON.stringify(product()) })); const firstBody = await first.json(); const second = await app().fetch(call("/api/admin/products", { method: "POST", headers, body: JSON.stringify(product()) })); expect(await second.json()).toEqual(firstBody); expect(writer.commits).toBe(1); const mismatch = await app().fetch(call("/api/admin/products", { method: "POST", headers, body: JSON.stringify(product({ name: "Другое" })) })); expect(mismatch.status).toBe(409); expect((await mismatch.json() as { error: { code: string } }).error.code).toBe("IDEMPOTENCY_CONFLICT"); });
  it("accepts a dimensioned PNG but rejects spoofed MIME, video and oversized files", async () => { const { cookie, csrf } = await login(); const png = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13, 0x49, 0x48, 0x44, 0x52, 0, 0, 0, 16, 0, 0, 0, 16]; expect((await upload(cookie, csrf, png, "image/png", "png-upload-key-000001")).status).toBe(201); expect((await upload(cookie, csrf, png, "image/jpeg", "spoof-upload-key-0001")).status).toBe(422); expect((await upload(cookie, csrf, png, "video/mp4", "video-upload-key-0001")).status).toBe(422); expect((await upload(cookie, csrf, [...new Uint8Array(10 * 1024 * 1024 + 1)], "image/jpeg", "large-upload-key-0001")).status).toBe(413); });
  it("allows only admin-staging as the staging write target", async () => {
    for (const ref of ["main", "master", "production", "live", "random-test"]) {
      const guarded = createApp(env, { store, writer, config: { ...config, environment: "staging", githubRef: ref, writesEnabled: true }, hasher: { algorithm: "test", hash: async (value) => value, verify: async (value, hash) => value === hash } });
      const response = await guarded.fetch(call("/api/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }));
      expect(response.status).toBe(503); expect((await response.json() as { error: { code: string } }).error.code).toBe("WRITE_TARGET_BLOCKED");
    }
    const allowed = createApp(env, { store, writer, config: { ...config, environment: "staging", githubRef: "admin-staging", writesEnabled: true }, hasher: { algorithm: "test", hash: async (value) => value, verify: async (value, hash) => value === hash } });
    expect((await allowed.fetch(call("/api/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }))).status).toBe(401);
  });
});
